### PR TITLE
Social Media Authentication Google

### PR DESCRIPTION
**Pull request by indeavila**
I followed the instructions given at: https://github.com/zquestz/omniauth-google-oauth2

Please use the following for the views files:
<%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %>

Hope this works.

### CODE REVIEW

**Comment by pawptart** [comment]
I would recommend creating all the views files you would need before submitting the PR (perhaps alter the Devise-generated login page to have an Omniauth link?). My fear is that if there is not a visible link, then this functionality will be forgotten, or worse, not tested.

I'm also curious if the Omniauth logins are working and tested. I know Google can take a few days to issue authentication credentials.

In the future, pull requests need to represent completed functionality (i.e. working code, tested, and everything present and visible). If this is not done then it can lead to some confusion.

**Comment by alifmomin1** [comment]
Should I go ahead and wait to accept the pull request? To make sure everything is working?

**Comment by indeavila** [comment]
I would then choose to not merge. I won't be able to work on this until 7:00pm PT.

**Comment by alifmomin1** [comment]
No worries! I'll go ahead and merge it once you've finalized everything! Thanks for the quick reply

**Comment by pawptart** [comment]
I'm going to go ahead and close this PR for now so that it doesn't accidentally get merged. It can be reopened later.

**Pull request closed without merging**
